# Generated by Django 6.0.1 on 2026-01-27 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bib_no', models.PositiveSmallIntegerField(unique=True)),
                ('yob', models.PositiveSmallIntegerField()),
                ('age_cat_id', models.ForeignKey(db_column='age_cat_id', on_delete=django.db.models.deletion.PROTECT, to='masters.agecategory')),
                ('diet_id', models.ForeignKey(db_column='diet_id', on_delete=django.db.models.deletion.PROTECT, to='masters.diet')),
                ('gender_id', models.ForeignKey(db_column='gender_id', on_delete=django.db.models.deletion.PROTECT, to='masters.gender')),
                ('school_id', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.PROTECT, to='school.school')),
                ('sec_id', models.ForeignKey(db_column='sec_id', on_delete=django.db.models.deletion.PROTECT, to='masters.section')),
                ('standard_id', models.ForeignKey(db_column='standard_id', on_delete=django.db.models.deletion.PROTECT, to='masters.standard')),
                ('yoga_sub_cat_id', models.ForeignKey(db_column='yoga_sub_cat_id', on_delete=django.db.models.deletion.PROTECT, to='masters.yogasubcat')),
            ],
            options={
                'db_table': 'participant',
            },
        ),
    ]
