# Generated by Django 6.0.1 on 2026-01-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='age_cat_id',
            new_name='age_cat',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='diet_id',
            new_name='diet',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='gender_id',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='school_id',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='sec_id',
            new_name='sec',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='standard_id',
            new_name='standard',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='yoga_sub_cat_id',
            new_name='yoga_sub_cat',
        ),
    ]
