# Generated by Django 6.0.1 on 2026-01-28 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bib_no', models.PositiveSmallIntegerField()),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('coc_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_coc', models.BooleanField(default=False)),
                ('age_cat', models.ForeignKey(db_column='age_cat_id', on_delete=django.db.models.deletion.PROTECT, to='masters.agecategory')),
                ('gender', models.ForeignKey(db_column='gender_id', on_delete=django.db.models.deletion.PROTECT, to='masters.gender')),
                ('yoga_sub_cat', models.ForeignKey(db_column='yoga_sub_cat_id', on_delete=django.db.models.deletion.PROTECT, to='masters.yogasubcat')),
            ],
            options={
                'db_table': 'score_individual',
            },
        ),
    ]
