# Generated by Django 6.0.1 on 2026-03-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthRole',
        ),
    ]
