# Generated by Django 6.0.1 on 2026-03-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_authrole'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthRole',
        ),
    ]
