# Generated by Django 6.0.1 on 2026-01-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('contact', models.BigIntegerField()),
                ('tic_no', models.BigIntegerField()),
                ('tic', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'school',
            },
        ),
    ]
