# Generated by Django 6.0.1 on 2026-01-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yob_min', models.PositiveSmallIntegerField()),
                ('yob_max', models.PositiveSmallIntegerField()),
                ('yoc', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'settings',
            },
        ),
    ]
